export interface CountryPhoneInfo {
  code: string; // ISO 2
  name: string;
  dialCode: string;
  flag: string;
}

export const WORLD_COUNTRIES: CountryPhoneInfo[] = [
  { code: "AF", name: "Afganistán", dialCode: "+93", flag: "🇦🇫" },
  { code: "AL", name: "Albania", dialCode: "+355", flag: "🇦🇱" },
  { code: "DE", name: "Alemania", dialCode: "+49", flag: "🇩🇪" },
  { code: "AD", name: "Andorra", dialCode: "+376", flag: "🇦🇩" },
  { code: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴" },
  { code: "SA", name: "Arabia Saudita", dialCode: "+966", flag: "🇸🇦" },
  { code: "DZ", name: "Argelia", dialCode: "+213", flag: "🇩🇿" },
  { code: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷" },
  { code: "AM", name: "Armenia", dialCode: "+374", flag: "🇦🇲" },
  { code: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺" },
  { code: "AT", name: "Austria", dialCode: "+43", flag: "🇦🇹" },
  { code: "AZ", name: "Azerbaiyán", dialCode: "+994", flag: "🇦🇿" },
  { code: "BS", name: "Bahamas", dialCode: "+1242", flag: "🇧🇸" },
  { code: "BD", name: "Bangladés", dialCode: "+880", flag: "🇧🇩" },
  { code: "BB", name: "Barbados", dialCode: "+1246", flag: "🇧🇧" },
  { code: "BE", name: "Bélgica", dialCode: "+32", flag: "🇧🇪" },
  { code: "BZ", name: "Belice", dialCode: "+501", flag: "🇧🇿" },
  { code: "BJ", name: "Benín", dialCode: "+229", flag: "🇧🇯" },
  { code: "BY", name: "Bielorrusia", dialCode: "+375", flag: "🇧🇾" },
  { code: "BO", name: "Bolivia", dialCode: "+591", flag: "🇧🇴" },
  { code: "BA", name: "Bosnia y Herzegovina", dialCode: "+387", flag: "🇧🇦" },
  { code: "BR", name: "Brasil", dialCode: "+55", flag: "🇧🇷" },
  { code: "BG", name: "Bulgaria", dialCode: "+359", flag: "🇧🇬" },
  { code: "KH", name: "Camboya", dialCode: "+855", flag: "🇰🇭" },
  { code: "CM", name: "Camerún", dialCode: "+237", flag: "🇨🇲" },
  { code: "CA", name: "Canadá", dialCode: "+1", flag: "🇨🇦" },
  { code: "QA", name: "Catar", dialCode: "+974", flag: "🇶🇦" },
  { code: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱" },
  { code: "CN", name: "China", dialCode: "+86", flag: "🇨🇳" },
  { code: "CY", name: "Chipre", dialCode: "+357", flag: "🇨🇾" },
  { code: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴" },
  { code: "KR", name: "Corea del Sur", dialCode: "+82", flag: "🇰🇷" },
  { code: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷" },
  { code: "HR", name: "Croacia", dialCode: "+385", flag: "🇭🇷" },
  { code: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺" },
  { code: "DK", name: "Dinamarca", dialCode: "+45", flag: "🇩🇰" },
  { code: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨" },
  { code: "EG", name: "Egipto", dialCode: "+20", flag: "🇪🇬" },
  { code: "SV", name: "El Salvador", dialCode: "+503", flag: "🇸🇻" },
  { code: "AE", name: "Emiratos Árabes Unidos", dialCode: "+971", flag: "🇦🇪" },
  { code: "SK", name: "Eslovaquia", dialCode: "+421", flag: "🇸🇰" },
  { code: "SI", name: "Eslovenia", dialCode: "+386", flag: "🇸🇮" },
  { code: "ES", name: "España", dialCode: "+34", flag: "🇪🇸" },
  { code: "US", name: "Estados Unidos", dialCode: "+1", flag: "🇺🇸" },
  { code: "EE", name: "Estonia", dialCode: "+372", flag: "🇪🇪" },
  { code: "PH", name: "Filipinas", dialCode: "+63", flag: "🇵🇭" },
  { code: "FI", name: "Finlandia", dialCode: "+358", flag: "🇫🇮" },
  { code: "FR", name: "Francia", dialCode: "+33", flag: "🇫🇷" },
  { code: "GE", name: "Georgia", dialCode: "+995", flag: "🇬🇪" },
  { code: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭" },
  { code: "GR", name: "Grecia", dialCode: "+30", flag: "🇬🇷" },
  { code: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹" },
  { code: "GN", name: "Guinea", dialCode: "+224", flag: "🇬🇳" },
  { code: "GQ", name: "Guinea Ecuatorial", dialCode: "+240", flag: "🇬🇶" },
  { code: "HT", name: "Haití", dialCode: "+509", flag: "🇭🇹" },
  { code: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳" },
  { code: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰" },
  { code: "HU", name: "Hungría", dialCode: "+36", flag: "🇭🇺" },
  { code: "IN", name: "India", dialCode: "+91", flag: "🇮🇳" },
  { code: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩" },
  { code: "IQ", name: "Irak", dialCode: "+964", flag: "🇮🇶" },
  { code: "IR", name: "Irán", dialCode: "+98", flag: "🇮🇷" },
  { code: "IE", name: "Irlanda", dialCode: "+353", flag: "🇮🇪" },
  { code: "IS", name: "Islandia", dialCode: "+354", flag: "🇮🇸" },
  { code: "IL", name: "Israel", dialCode: "+972", flag: "🇮🇱" },
  { code: "IT", name: "Italia", dialCode: "+39", flag: "🇮🇹" },
  { code: "JM", name: "Jamaica", dialCode: "+1876", flag: "🇯🇲" },
  { code: "JP", name: "Japón", dialCode: "+81", flag: "🇯🇵" },
  { code: "JO", name: "Jordania", dialCode: "+962", flag: "🇯🇴" },
  { code: "KZ", name: "Kazajistán", dialCode: "+7", flag: "🇰🇿" },
  { code: "KE", name: "Kenia", dialCode: "+254", flag: "🇰🇪" },
  { code: "KW", name: "Kuwait", dialCode: "+965", flag: "🇰🇼" },
  { code: "LB", name: "Líbano", dialCode: "+961", flag: "🇱🇧" },
  { code: "LU", name: "Luxemburgo", dialCode: "+352", flag: "🇱🇺" },
  { code: "MY", name: "Malasia", dialCode: "+60", flag: "🇲🇾" },
  { code: "MA", name: "Marruecos", dialCode: "+212", flag: "🇲🇦" },
  { code: "MX", name: "México", dialCode: "+52", flag: "🇲🇽" },
  { code: "MC", name: "Mónaco", dialCode: "+377", flag: "🇲🇨" },
  { code: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿" },
  { code: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮" },
  { code: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬" },
  { code: "NO", name: "Noruega", dialCode: "+47", flag: "🇳🇴" },
  { code: "NZ", name: "Nueva Zelanda", dialCode: "+64", flag: "🇳🇿" },
  { code: "NL", name: "Países Bajos", dialCode: "+31", flag: "🇳🇱" },
  { code: "PA", name: "Panamá", dialCode: "+507", flag: "🇵🇦" },
  { code: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾" },
  { code: "PE", name: "Perú", dialCode: "+51", flag: "🇵🇪" },
  { code: "PL", name: "Polonia", dialCode: "+48", flag: "🇵🇱" },
  { code: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹" },
  { code: "PR", name: "Puerto Rico", dialCode: "+1787", flag: "🇵🇷" },
  { code: "GB", name: "Reino Unido", dialCode: "+44", flag: "🇬🇧" },
  { code: "CZ", name: "República Checa", dialCode: "+420", flag: "🇨🇿" },
  { code: "DO", name: "República Dominicana", dialCode: "+1809", flag: "🇩🇴" },
  { code: "RO", name: "Rumania", dialCode: "+40", flag: "🇷🇴" },
  { code: "RU", name: "Rusia", dialCode: "+7", flag: "🇷🇺" },
  { code: "SN", name: "Senegal", dialCode: "+221", flag: "🇸🇳" },
  { code: "SG", name: "Singapur", dialCode: "+65", flag: "🇸🇬" },
  { code: "ZA", name: "Sudáfrica", dialCode: "+27", flag: "🇿🇦" },
  { code: "SE", name: "Suecia", dialCode: "+46", flag: "🇸🇪" },
  { code: "CH", name: "Suiza", dialCode: "+41", flag: "🇨🇭" },
  { code: "TH", name: "Tailandia", dialCode: "+66", flag: "🇹🇭" },
  { code: "TW", name: "Taiwán", dialCode: "+886", flag: "🇹🇼" },
  { code: "TR", name: "Turquía", dialCode: "+90", flag: "🇹🇷" },
  { code: "UA", name: "Ucrania", dialCode: "+380", flag: "🇺🇦" },
  { code: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾" },
  { code: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪" },
  { code: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳" },
];
